config/routes.rb
Rails.application.routes.draw do
  get 'admins/index'

  get 'home' => 'home#index'
  devise_scope :user do
   authenticated :user do
     root 'home#index', as: :authenticated_root
   end

   unauthenticated do
     root 'devise/sessions#new', as: :unauthenticated_root
   end
  end
  
  resources :employs
  resources :admins do
    collection do
      get :assign_employ 
    end
  end

  devise_for :users

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  belongs_to :employ
end

app/models/apm.rb
class Apm < ActiveRecord::Base
  has_many :teamleads
  has_many :projects
  belongs_to :employ
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  belongs_to :employ
  belongs_to :teamlead
  has_many :projects
end

app/models/employ.rb
class Employ < ActiveRecord::Base
  has_many :developers
  has_one :user
  accepts_nested_attributes_for :user
  after_save :check_role

  def check_role
    if self.role == 'admin'
       if Admin.all.count == 0
         admin = Admin.new
         admin.employ_id = self.id
         admin.save
       end
    elsif self.role == 'apm'
       apm = Apm.new
       apm.employ_id = self.id
       apm.save
    elsif self.role == 'teamlead'
       teamlead = Teamlead.new
       teamlead.employ_id = self.id
       teamlead.save
    else 
       developer = Developer.new
       developer.employ_id = self.id
       developer.save
    end
  end

  def admin?
    if self.role == 'admin'
    	return true
    end
  end

  def developer?
    if self.role == 'developer'
    	return true 
    end
  end

  def apm?
    if self.role == 'apm'
    	return true
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :apm
  belongs_to :teamlead
  belongs_to :developer
end

app/models/teamlead.rb
class Teamlead < ActiveRecord::Base
  belongs_to :apm
  has_many :projects
  has_many :developers
  belongs_to :employ
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :employ
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @employ = Employ.all
  end

  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @employs = Employ.all
  end

  def assign_employ
  	@employ = Employ.find(params[:employ])
    #@array = AdminsHelper.get_employ(params[:employ]) 
    @employees = if @employ.role == 'developer'
                   Teamlead.all
                 elsif @employ.role == 'teamlead'
                   Apm.all
                 else 
    	           [0,1]
                 end
   redirect_to :controller => 'employs', :action => 'edit', :id => params[:employ] 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employs_controller.rb
class EmploysController < ApplicationController

  def index
    @employs = Employ.all
  end

  def new
    @employ = Employ.new
    @employ.build_user
  end

  def create
    @employ = Employ.new(employ_params)
    @employ.save
    redirect_to :controller => 'home', :action => 'index'
  end

  def edit
    @employ = Employ.find(params[:id])
    @employees = if @employ.role == 'developer'
                   Teamlead.all
                 elsif @employ.role == 'teamlead'
                   Apm.all
                 else 
                 [0,1]
                 end
  # render :json => params
  # return
  end

  def update
    # render :json => params
    # return
    @employ = Employ.find(params[:id])
    status = if @employ.role == 'developer'
               Teamlead.find(params[:employ][:status])
             elsif @employ.role == 'teamlead'
               Apm.find(params[:employ][:status])
             else 
               [0,1]
             end
    if @employ.update_attributes(params[:employ])
      # @employ.status = status.employ.first_name
     #  render :json => @employ
    #   return
     # flash[:notice] = 'Employ was successfully updated.'

      redirect_to(@employ)
    else
      render "edit"
    end
    render :json => @employ
    return
  end

  private

    def employ_params
      params.require(:employ).permit(:first_name, :last_name, :role, :contact,:status , :address ,:user_attributes => [:email , :password , :password_confirmation])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require "oauth2"
  def index
  	@profile = current_user.employ
  	

	client = OAuth2::Client.new(
	  "98359272074-9a6gcmvf86on47i1bu936pickdukdai7.apps.googleusercontent.com",
	  "hHazErulh8NiKRr7qdVSE78h", 
	  :authorize_url => "/oauth2/authorize", 
	  :token_url => "/oauth2/access_token", 
	  :site => "https://www.googleapis.com/admin/"
	)

	puts client.auth_code.authorize_url(:redirect_uri => "http://localhost:3000")

	code = gets.chomp
	puts "the code is #{code}"

	token = client.auth_code.get_token(code,:redirect_uri => "http://localhost:3000")

	token = OAuth2::AccessToken.new(client, token.token, {
	  :mode => :query,
	  :param_name => "oauth_token",
	})

	response = token.get('https://www.googleapis.com/admin/directory/v1/groups/dipanshu-group/members')

	puts response.body

# 	require 'oauth2'
# 	client = OAuth2::Client.new('645267522106.apps.googleusercontent.com', 'HgWirYGuhCiKHxdYOIcMiFxN', :site => 'https://www.googleapis.com/auth/admin.directory.group')

# 	client.auth_code.authorize_url(:redirect_uri => 'http://localhost:3000')
# # => "https://example.org/oauth/authorization?response_type=code&client_id=client_id&redirect_uri=http://localhost:8080/oauth2/callback"

# 	token = client.auth_code.get_token('authorization_code_value', :redirect_uri => 'http://localhost:3000')
# 	puts "the token is #{token}"
# 	response = token.get('/api/resource', :params => { 'query_foo' => 'bar' })
# 	response.class.name
	end

  
end

app/helpers/admins_helper.rb
module AdminsHelper

  def self.get_employ(id)
    employ = Employ.find(id)
    if employ.role == 'developer'
      teamlead = Teamlead.all
    elsif employ.role == 'teamlead'
      apm = Apm.all
    else 
    	return []
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employs_helper.rb
module EmploysHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/assign_employ.html.haml
%h2 Assign Role
%p
  %b First Name
  = @employ.first_name

%p
  %b Last Name
  = @employ.last_name

%p
  %b Role
  = @employ.role

%p
  - if @employ.role == 'developer'
    %b Assign TeamLead
    = select_tag @employ.address , options_for_select(@employees.map {|teamlead| teamlead.employ.first_name})
  - if @employ.role == 'teamlead'
    %b Assign Apm
    = select_tag @employ.address , options_for_select(@employees.map {|apm| apm.employ.first_name})

  

app/views/admins/index.html.haml
%h1 Listing User
%table.table
  %tr
    %th First Name
    %th Last Name
    %th Contact
    %th Address
    %th Role
    %th Status
    %th
    %th 
    %th
  
  - @employs.each do |employ|
    %tr
      %td= employ.first_name
      %td= employ.last_name
      %td= employ.contact
      %td= employ.address
      %td= employ.role
      %td= link_to employ.status , assign_employ_admins_path(:employ => employ) 
      %td= link_to 'edit'
      %td= link_to 'show'
      %td= link_to 'delete'

%br
= link_to 'New Employ'

app/views/employs/_form.html.haml
= form_for @employ do |f|
  - if @employ.errors.any?
    #error_explanation
      %h2= "#{pluralize(@employ.errors.count, "error")} prohibited this employ from being saved:"
      %ul
        - @employ.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :contact
    = f.text_field :contact
  .field
    = f.label :role
    = f.text_field :role
  .field
    = f.label :status
    - if @employ.role == 'developer'
      %b Assign TeamLead
      = f.select :status , options_for_select(@employees.map {|teamlead| teamlead.employ.first_name})
    - if @employ.role == 'teamlead'
      %b Assign Apm
      = f.select :status , options_for_select(@employees.map {|apm| apm.employ.first_name})

  .field
    = f.label :address
    = f.text_area :address
  .actions
    = f.submit 'Save'

app/views/employs/edit.html.haml
%h1 Editing employ

= form_for @employ do |f|
  - if @employ.errors.any?
    #error_explanation
      %h2= "#{pluralize(@employ.errors.count, "error")} prohibited this employ from being saved:"
      %ul
        - @employ.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :contact
    = f.text_field :contact
  .field
    = f.label :role
    = f.text_field :role
  .field
    = f.label :status
    - if @employ.role == 'developer'
      %b Assign TeamLead
      = f.select :status , options_for_select(@employees.map {|teamlead| [teamlead.employ.first_name , teamlead.id]})
    - if @employ.role == 'teamlead'
      %b Assign Apm
      = f.select :status , options_for_select(@employees.map {|apm| [apm.employ.first_name ,apm.id ]})

  .field
    = f.label :address
    = f.text_area :address
  .actions
    = f.submit 'Save'


= link_to 'Show', @employ
\|
= link_to 'Back', employs_path

app/views/employs/index.html.haml
%h1 Listing employs

%table.table
  %tr
    %th first_name
    %th Last name
    %th Contact
    %th Address
    %th 
    %th
    %th

  - @employs.each do |employ|
    %tr
      %td= employ.first_name
      %td= employ.last_name
      %td= employ.contact
      %td= employ.address
      %td= link_to 'Show', employ
      %td= link_to 'Edit', edit_employ_path(employ)
      %td= link_to 'Destroy', employ, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Employ', new_employ_path

app/views/employs/new.html.haml
%h1 New employ

= form_for @employ do |f|
  - if @employ.errors.any?
    #error_explanation
      %h2= "#{pluralize(@employ.errors.count, "error")} prohibited this employ from being saved:"
      %ul
        - @employ.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name , :required => true
  .field
    = f.label :last_name
    = f.text_field :last_name , :required => true
  .field
    = f.label :role
    = f.select :role, options_for_select(%w[admin developer apm teamlead] , selected: "employ", disabled: "admin")
  .field
    = f.label :contact
    = f.text_field :contact , :required => true
  .field
    = f.label :address
    = f.text_area :address , :required => true
  = f.fields_for :user do |u|
    .field
      = u.label :email
      = u.email_field :email , :required => true
    .field
      = u.label :password
      = u.password_field :password , :required => true
    .field
      = u.label :password_confirmation
      = u.password_field :password_confirmation , :required => true

  .actions
    = f.submit 'Save'

= link_to 'Back', employs_path

app/views/employs/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @employ.first_name
%p
  %b Last name:
  = @employ.last_name
%p
  %b Contact:
  = @employ.contact
%p
  %b Address:
  = @employ.address

= link_to 'Edit', edit_employ_path(@employ)
\|
= link_to 'Back', employs_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "CmsProject"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") CmsProject
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Link 1", "/path1"
            %li= link_to "Link 2", "/path2"
            %li= link_to "Link 3", "/path3"
            - if current_user 
              %li= link_to "Sign out", destroy_user_session_path, :method => :delete 
    

          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Link 1",'#'
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                #{current_user.employ.first_name}
                %span.caret
              %ul.dropdown-menu(role="menu")
                %li= link_to "Action","#"
                %li= link_to "Action","#"
                %li= link_to "Action","#"
                - if current_user 
                  %li= link_to "Sign out", destroy_user_session_path, :method => :delete 
              
            

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        
      %footer
        %p &copy; Company 2014